version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Production environment variables
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8000/api/v1}
        VITE_API_TIMEOUT: ${VITE_API_TIMEOUT:-30000}
        VITE_APP_NAME: ${VITE_APP_NAME:-URL Analyzer}
        VITE_APP_VERSION: ${VITE_APP_VERSION:-1.0.0}
        VITE_AUTH_STORAGE_KEY: ${VITE_AUTH_STORAGE_KEY:-webAnalyzer_auth}
        VITE_DEBUG_MODE: ${VITE_DEBUG_MODE:-false}
        VITE_ENABLE_ANALYTICS: ${VITE_ENABLE_ANALYTICS:-false}
    container_name: url-analyzer-frontend-prod
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - url-analyzer-network
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  backend:
    image: url-analyzer-backend:latest
    container_name: url-analyzer-backend-prod
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - url-analyzer-network

networks:
  url-analyzer-network:
    driver: bridge

volumes:
  nginx_logs:
    driver: local
