# Production Docker Compose configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
version: '3.8'

services:
  app:
    environment:
      - DEBUG=false
      - SERVER_RELOAD=false
      - SERVER_LOG_LEVEL=info
    # Remove volume mounts for production
    volumes: []
    # Use production command without reload - migrations will run automatically via startup.sh
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    # Add resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped

  postgres:
    # Don't expose postgres port in production
    ports: []
    # Add resource limits for production
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: unless-stopped
    # Add production-specific PostgreSQL configuration
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
