version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: url_analyzer_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/url_analyzer_db
      - SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - SERVER_RELOAD=true
      - SERVER_LOG_LEVEL=debug
      - DEBUG=true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - .:/app:cached
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
